sudo: required
services:
    - docker

before_install:
    - docker build -t 3n01/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
    - docker run 3n01/multi-docker-test npm test -- --coverage

after_success:
    - docker build -t 3n01/multi-client ./client
    - docker build -t 3n01/multi-nginx ./nginx
    - docker build -t 3n01/multi-server ./server
    - docker build -t 3n01/multi-worker ./worker
    # log in to th docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them to docker hub
    - docker push 3n01/multi-client 
    - docker push 3n01/multi-nginx 
    - docker push 3n01/multi-server 
    - docker push 3n01/multi-worker 


